import type { Service } from '@/types'

export const services: Service[] = [
  // INTRADAY ALPHA
  {
    id: 'intraday-alpha-1m',
    title: 'Intraday Alpha — 1 Month',
    category: 'Equity Cash',
    duration: '1 Month',
    price: '₹5,000',
    tag: 'Most Popular',
    targetAudience: 'Trader',
    description: 'Intraday Alpha is a cash-market intraday trading research service designed for traders looking to capture short-term opportunities within the same trading day. Our research professionals analyze market movements using structured technical methods to identify high-potential trading setups.',
    features: [
      '1–2 intraday trades per day',
      'Same day exit — no overnight risk',
      'Telegram alerts',
      'Entry, target & stop-loss defined',
      'Real-time trade updates',
      'Research report included',
      'Dedicated support',
    ],
  },
  {
    id: 'intraday-alpha-3m',
    title: 'Intraday Alpha — 3 Months',
    category: 'Equity Cash',
    duration: '3 Months',
    price: '₹12,000',
    tag: 'Best Value',
    targetAudience: 'Trader',
    description: 'Intraday Alpha is a cash-market intraday trading research service designed for traders looking to capture short-term opportunities within the same trading day. Our research professionals analyze market movements using structured technical methods to identify high-potential trading setups.',
    features: [
      '1–2 intraday trades per day',
      'Same day exit — no overnight risk',
      'Telegram alerts',
      'Entry, target & stop-loss defined',
      'Real-time trade updates',
      'Research report included',
      'Dedicated support',
    ],
  },
  {
    id: 'intraday-alpha-1y',
    title: 'Intraday Alpha — Annual',
    category: 'Equity Cash',
    duration: '12 Months',
    price: '₹36,000',
    tag: null,
    targetAudience: 'Trader',
    description: 'Intraday Alpha is a cash-market intraday trading research service designed for traders looking to capture short-term opportunities within the same trading day. Our research professionals analyze market movements using structured technical methods to identify high-potential trading setups.',
    features: [
      '1–2 intraday trades per day',
      'Same day exit — no overnight risk',
      'Telegram alerts',
      'Entry, target & stop-loss defined',
      'Real-time trade updates',
      'Research report included',
      'Dedicated support',
    ],
  },

  // BTST ALPHA
  {
    id: 'btst-alpha-1m',
    title: 'BTST Alpha — 1 Month',
    category: 'Equity Premium',
    duration: '1 Month',
    price: '₹5,000',
    tag: 'Most Popular',
    targetAudience: 'Trader',
    description: 'BTST Alpha (Buy Today, Sell Tomorrow) is designed for traders who want to benefit from potential overnight price momentum in carefully selected stocks. Take a position near the end of the trading session and exit the next day to capture favourable price movements.',
    features: [
      '1 high-conviction BTST trade per day',
      'Exit next morning',
      'Alerts issued 2:45 PM – 3:15 PM',
      'Telegram alerts',
      'Entry, target & stop-loss defined',
      'Research report included',
      'Dedicated support',
    ],
  },
  {
    id: 'btst-alpha-3m',
    title: 'BTST Alpha — 3 Months',
    category: 'Equity Premium',
    duration: '3 Months',
    price: '₹12,000',
    tag: 'Best Value',
    targetAudience: 'Trader',
    description: 'BTST Alpha (Buy Today, Sell Tomorrow) is designed for traders who want to benefit from potential overnight price momentum in carefully selected stocks. Take a position near the end of the trading session and exit the next day to capture favourable price movements.',
    features: [
      '1 high-conviction BTST trade per day',
      'Exit next morning',
      'Alerts issued 2:45 PM – 3:15 PM',
      'Telegram alerts',
      'Entry, target & stop-loss defined',
      'Research report included',
      'Dedicated support',
    ],
  },
  {
    id: 'btst-alpha-1y',
    title: 'BTST Alpha — Annual',
    category: 'Equity Premium',
    duration: '12 Months',
    price: '₹36,000',
    tag: null,
    targetAudience: 'Trader',
    description: 'BTST Alpha (Buy Today, Sell Tomorrow) is designed for traders who want to benefit from potential overnight price momentum in carefully selected stocks. Take a position near the end of the trading session and exit the next day to capture favourable price movements.',
    features: [
      '1 high-conviction BTST trade per day',
      'Exit next morning',
      'Alerts issued 2:45 PM – 3:15 PM',
      'Telegram alerts',
      'Entry, target & stop-loss defined',
      'Research report included',
      'Dedicated support',
    ],
  },

  // POSITIONAL ALPHA
  {
    id: 'positional-alpha-1m',
    title: 'Positional Alpha — 1 Month',
    category: 'F&O',
    duration: '1 Month',
    price: '₹6,000',
    tag: null,
    targetAudience: 'Trader',
    description: 'Positional Alpha is a positional trading research service designed for traders who want to benefit from short-term market trends without the pressure of daily trading. Hold stocks for several days to a few weeks to capture meaningful price movements.',
    features: [
      '3–4 trades per month',
      'Holding period approx. 2 weeks',
      'Telegram alerts',
      'Entry, target & stop-loss defined',
      'Ongoing trade updates',
      'Research report included',
      'Dedicated support',
    ],
  },
  {
    id: 'positional-alpha-3m',
    title: 'Positional Alpha — 3 Months',
    category: 'F&O',
    duration: '3 Months',
    price: '₹15,000',
    tag: 'Best Value',
    targetAudience: 'Trader',
    description: 'Positional Alpha is a positional trading research service designed for traders who want to benefit from short-term market trends without the pressure of daily trading. Hold stocks for several days to a few weeks to capture meaningful price movements.',
    features: [
      '3–4 trades per month',
      'Holding period approx. 2 weeks',
      'Telegram alerts',
      'Entry, target & stop-loss defined',
      'Ongoing trade updates',
      'Research report included',
      'Dedicated support',
    ],
  },
  {
    id: 'positional-alpha-1y',
    title: 'Positional Alpha — Annual',
    category: 'F&O',
    duration: '12 Months',
    price: '₹48,000',
    tag: null,
    targetAudience: 'Trader',
    description: 'Positional Alpha is a positional trading research service designed for traders who want to benefit from short-term market trends without the pressure of daily trading. Hold stocks for several days to a few weeks to capture meaningful price movements.',
    features: [
      '3–4 trades per month',
      'Holding period approx. 2 weeks',
      'Telegram alerts',
      'Entry, target & stop-loss defined',
      'Ongoing trade updates',
      'Research report included',
      'Dedicated support',
    ],
  },

  // DEMO / TRIAL PLANS
  {
    id: 'intraday-alpha-demo',
    title: 'Intraday Alpha — Trial',
    category: 'Equity Cash',
    duration: '7 Days',
    price: '₹300',
    tag: 'Free Trial',
    targetAudience: 'Trader',
    isTrial: true,
    description: 'Try Intraday Alpha for 7 days at a minimal cost before committing to a full plan.',
    features: ['1–2 intraday trades', 'Telegram alerts', 'Entry, target & stop-loss', 'No commitment'],
  },
  {
    id: 'btst-alpha-demo',
    title: 'BTST Alpha — Trial',
    category: 'Equity Premium',
    duration: '7 Days',
    price: '₹300',
    tag: 'Free Trial',
    targetAudience: 'Trader',
    isTrial: true,
    description: 'Try BTST Alpha for 7 days at a minimal cost before committing to a full plan.',
    features: ['1 BTST trade', 'Telegram alerts', 'Entry, target & stop-loss', 'No commitment'],
  },
  {
    id: 'positional-alpha-demo',
    title: 'Positional Alpha — Trial',
    category: 'F&O',
    duration: '7 Days',
    price: '₹300',
    tag: 'Free Trial',
    targetAudience: 'Trader',
    isTrial: true,
    description: 'Try Positional Alpha for 7 days at a minimal cost before committing to a full plan.',
    features: ['1–2 positional trades', 'Telegram alerts', 'Entry, target & stop-loss', 'No commitment'],
  },
  {
    id: 'free-demo-service',
    title: 'Free Demo Service',
    category: 'Trial Plans',
    duration: '2 Days',
    price: '₹118',
    tag: 'Free Trial',
    targetAudience: 'Trader',
    isTrial: true,
    description: 'Experience our research quality with a 2-day demo at a minimal cost. No commitment required.',
    features: ['Live trade alerts', 'Telegram alerts', 'Entry, target & stop-loss', 'No commitment'],
  },

  // CAPITAL COMPOUNDERS — INVESTOR SERVICE
  {
    id: 'capital-compounders-1m',
    title: 'Capital Compounders — 1 Month',
    category: 'Investor',
    duration: '1 Month',
    price: '₹3,000',
    tag: null,
    targetAudience: 'Investor',
    description: 'Medium-term equity strategy focusing on fundamentally strong companies for consistent compounding. 1 high-conviction recommendation per month.',
    features: [
      '1 Trade/Month',
      '12-24 Month Hold',
      '25-35% Target Return',
      'Detailed investment rationale report',
      'Quarterly updates on open positions',
      'Telegram alerts',
      'Dedicated support',
    ],
  },
  {
    id: 'capital-compounders-3m',
    title: 'Capital Compounders — 3 Months',
    category: 'Investor',
    duration: '3 Months',
    price: '₹7,500',
    tag: 'Best Value',
    targetAudience: 'Investor',
    description: 'Medium-term equity strategy focusing on fundamentally strong companies for consistent compounding. 1 high-conviction recommendation per month.',
    features: [
      '1 Trade/Month',
      '12-24 Month Hold',
      '25-35% Target Return',
      'Detailed investment rationale report',
      'Quarterly updates on open positions',
      'Telegram alerts',
      'Dedicated support',
    ],
  },
  {
    id: 'capital-compounders-1y',
    title: 'Capital Compounders — Annual',
    category: 'Investor',
    duration: '12 Months',
    price: '₹23,000',
    tag: 'Most Popular',
    targetAudience: 'Investor',
    description: 'Medium-term equity strategy focusing on fundamentally strong companies for consistent compounding. 1 high-conviction recommendation per month.',
    features: [
      '1 Trade/Month',
      '12-24 Month Hold',
      '25-35% Target Return',
      'Detailed investment rationale report',
      'Quarterly updates on open positions',
      'Telegram alerts',
      'Dedicated support',
    ],
  },
]
